TWAmazon::Application.routes.draw do

  root :to => 'home#login'

  # define an index or home path to redirect if a user already login
  match 'home', :to => 'SilentAuctions#index', :as => :index

  # silent auctions paths
  resources :silent_auctions, :only => [:create, :new, :index]


  # Paths generated by devise for user authentication:
  # user_omniauth_authorize_path(provider)
  # user_omniauth_callback_path(provider)
  devise_for :users,
             :controllers => { :omniauth_callbacks => "sessions", :sessions => "dummy_sessions" },
             :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  devise_scope :user do
    get '/login', :to => "sessions#new", :as => :new_user_session
    get '/logout_cas', :to => 'sessions#destroy_cas', :as => :destroy_cas_user_session

    # for dummy user accounts
    get '/users/login', :to => 'dummy_sessions#new', :as => :new_dummy_session
    get '/users/logout', :to => 'dummy_sessions#destroy', :as => :destroy_user_session
  end

end
