TWAmazon::Application.routes.draw do

  #root :to => 'SilentAuctions#index'

  resources :silent_auctions, :only => [:create, :new, :index]

  # Paths generated by devise for user authentication:
  # user_omniauth_authorize_path(provider)
  # user_omniauth_callback_path(provider)
  devise_for :users, :controllers => { :omniauth_callbacks => "sessions"}

  devise_scope :user do
    match "/" => "sessions#new"
    get 'sign_in', :to => 'sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'sessions#destroy', :as => :destroy_user_session
    get 'sign_out_cas', :to => 'sessions#destroy_cas', :as => :destroy_cas_session
  end

end
